### ISSUE TITLE
Cannot paste to search box

### ISSUE THREAD

**Issue by KnIfER** [TagWolf/auto-select-pasted-text#3]
when trying to paste text to find box (ctrl+f, ctrl+v), the text is pasted to editor instead. 

according to the [doc](https://code.visualstudio.com/api/references/vscode-api)

![image](https://github.com/davidpcahill/auto-select-pasted-text/assets/11593903/7634f1f0-f877-4a79-8757-66b9639ef5ba)

 vscode.window.activeTextEditor could be unfocused. 

```
vscode: 1.64.0 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 10.0.19044
```

**Comment by ldevoco** [comment]
I re-created this since it seems it's still happening:
https://github.com/davidpcahill/auto-select-pasted-text/issues/4
